usage:	java org.teherba.checkdig.DigitChecker [-f filename] [-m html]
      	     -account <German Account Number> -blz <German BLZ>
      	     -ean     <EAN-13 or EAN-8>        
      	     -iban    <IBAN>     
      	     -isbn    <ISBN-13 or ISBN-10>     
      	     -isin    <ISIN>     
      	     -ismn    <ISMN-13 or ISMN-10>     
      	     -issn    <ISSN>     
      	     -pnd     <PND>      
      	     -taxid   <German Tax Identification Number>
      	     -uci     <SEPA Unique Creditor Id>
      	     -vatid   <VAT-Id Number>
