/*  BlzDetailBeanBase.java - 
 *  @(#) $Id$
 *  Automatically generated by xtrans/web/xslt/genRecord.xsl at 2014-01-22T14:22:12+01:00
 *  DO NOT EDIT HERE - rather inherit from this class!
 */
package org.teherba.checkdig.account;
import  java.text.SimpleDateFormat;
import  java.sql.Date;
import  java.sql.Timestamp;
import  org.xml.sax.Attributes;
import  org.xml.sax.helpers.AttributesImpl;
import  org.xml.sax.SAXException;

/** .
 */
public class BlzDetailBeanBase {
    /** Readable format for dates */
    protected static final SimpleDateFormat ISO_DATE_FORMAT      = new SimpleDateFormat("yyyy-MM-dd");
    /** Readable format for timestamps with milliseconds */
    protected static final SimpleDateFormat ISO_TIMESTAMP_FORMAT = new SimpleDateFormat("yyyy-MM-dd HH:mm:ss.SSS");

    /** Replaces offending characters in attributes by entities,
     *  and trim right trailing whitespace
     *  @param value value of the attribute
     *  @return string with offending characters replaced by entities
     */
    protected String replaceAttrText(String value) {
        return ("x" + value
                .replaceAll("&" , "&amp;")
                .replaceAll("\'", "&apos;")
                .replaceAll("\"", "&quot;")
               ).trim().substring(1);
    } // replaceAttrText

    /** Source code version */
    public static final String CVSID = "@(#) $Id$";


    /** No-args Constructor for .
     */
    public BlzDetailBeanBase() {
        super();
    } // Constructor

    /** blz - Bankleitzahl */
    protected String blz;

    /** Sets blz - Bankleitzahl
     *  @param blz Bankleitzahl
     */
    public void setBlz(String blz) {
        this.blz = blz;
    } // setBlz

    /** Gets blz - Bankleitzahl
     *  @return Bankleitzahl
     */
    public String getBlz() {
        return blz;
    } // getBlz
    //----------------
    /** fuehrend - 1(2) = (nicht) führend */
    protected String fuehrend;

    /** Sets fuehrend - 1(2) = (nicht) führend
     *  @param fuehrend 1(2) = (nicht) führend
     */
    public void setFuehrend(String fuehrend) {
        this.fuehrend = fuehrend;
    } // setFuehrend

    /** Gets fuehrend - 1(2) = (nicht) führend
     *  @return 1(2) = (nicht) führend
     */
    public String getFuehrend() {
        return fuehrend;
    } // getFuehrend
    //----------------
    /** institut - Kreditinstitut */
    protected String institut;

    /** Sets institut - Kreditinstitut
     *  @param institut Kreditinstitut
     */
    public void setInstitut(String institut) {
        this.institut = institut;
    } // setInstitut

    /** Gets institut - Kreditinstitut
     *  @return Kreditinstitut
     */
    public String getInstitut() {
        return institut;
    } // getInstitut
    //----------------
    /** plz - Postleitzahl */
    protected String plz;

    /** Sets plz - Postleitzahl
     *  @param plz Postleitzahl
     */
    public void setPlz(String plz) {
        this.plz = plz;
    } // setPlz

    /** Gets plz - Postleitzahl
     *  @return Postleitzahl
     */
    public String getPlz() {
        return plz;
    } // getPlz
    //----------------
    /** ort - Ort */
    protected String ort;

    /** Sets ort - Ort
     *  @param ort Ort
     */
    public void setOrt(String ort) {
        this.ort = ort;
    } // setOrt

    /** Gets ort - Ort
     *  @return Ort
     */
    public String getOrt() {
        return ort;
    } // getOrt
    //----------------
    /** inst - Institutskurzname */
    protected String inst;

    /** Sets inst - Institutskurzname
     *  @param inst Institutskurzname
     */
    public void setInst(String inst) {
        this.inst = inst;
    } // setInst

    /** Gets inst - Institutskurzname
     *  @return Institutskurzname
     */
    public String getInst() {
        return inst;
    } // getInst
    //----------------
    /** instNr - Institutsnummer */
    protected String instNr;

    /** Sets instNr - Institutsnummer
     *  @param instNr Institutsnummer
     */
    public void setInstNr(String instNr) {
        this.instNr = instNr;
    } // setInstNr

    /** Gets instNr - Institutsnummer
     *  @return Institutsnummer
     */
    public String getInstNr() {
        return instNr;
    } // getInstNr
    //----------------
    /** bic - Bank Identifier Code */
    protected String bic;

    /** Sets bic - Bank Identifier Code
     *  @param bic Bank Identifier Code
     */
    public void setBic(String bic) {
        this.bic = bic;
    } // setBic

    /** Gets bic - Bank Identifier Code
     *  @return Bank Identifier Code
     */
    public String getBic() {
        return bic;
    } // getBic
    //----------------
    /** pzMethode - Prüfziffernmethode */
    protected String pzMethode;

    /** Sets pzMethode - Prüfziffernmethode
     *  @param pzMethode Prüfziffernmethode
     */
    public void setPzMethode(String pzMethode) {
        this.pzMethode = pzMethode;
    } // setPzMethode

    /** Gets pzMethode - Prüfziffernmethode
     *  @return Prüfziffernmethode
     */
    public String getPzMethode() {
        return pzMethode;
    } // getPzMethode
    //----------------
    /** satzNr - seq  Satznummer */
    protected String satzNr;

    /** Sets satzNr - seq  Satznummer
     *  @param satzNr seq  Satznummer
     */
    public void setSatzNr(String satzNr) {
        this.satzNr = satzNr;
    } // setSatzNr

    /** Gets satzNr - seq  Satznummer
     *  @return seq  Satznummer
     */
    public String getSatzNr() {
        return satzNr;
    } // getSatzNr
    //----------------
    /** aendKnz - (A)dd,(D)el,(U)nch,(M)od */
    protected String aendKnz;

    /** Sets aendKnz - (A)dd,(D)el,(U)nch,(M)od
     *  @param aendKnz (A)dd,(D)el,(U)nch,(M)od
     */
    public void setAendKnz(String aendKnz) {
        this.aendKnz = aendKnz;
    } // setAendKnz

    /** Gets aendKnz - (A)dd,(D)el,(U)nch,(M)od
     *  @return (A)dd,(D)el,(U)nch,(M)od
     */
    public String getAendKnz() {
        return aendKnz;
    } // getAendKnz
    //----------------
    /** loeschung - 1 (0) fuer zuk  Löschung */
    protected String loeschung;

    /** Sets loeschung - 1 (0) fuer zuk  Löschung
     *  @param loeschung 1 (0) fuer zuk  Löschung
     */
    public void setLoeschung(String loeschung) {
        this.loeschung = loeschung;
    } // setLoeschung

    /** Gets loeschung - 1 (0) fuer zuk  Löschung
     *  @return 1 (0) fuer zuk  Löschung
     */
    public String getLoeschung() {
        return loeschung;
    } // getLoeschung
    //----------------
    /** folgeBlz - Folge-BLZ (wenn Löschg=1) */
    protected String folgeBlz;

    /** Sets folgeBlz - Folge-BLZ (wenn Löschg=1)
     *  @param folgeBlz Folge-BLZ (wenn Löschg=1)
     */
    public void setFolgeBlz(String folgeBlz) {
        this.folgeBlz = folgeBlz;
    } // setFolgeBlz

    /** Gets folgeBlz - Folge-BLZ (wenn Löschg=1)
     *  @return Folge-BLZ (wenn Löschg=1)
     */
    public String getFolgeBlz() {
        return folgeBlz;
    } // getFolgeBlz
    //----------------
    /** ibanRegel - Nummer der IBAN-Regel */
    protected String ibanRegel;

    /** Sets ibanRegel - Nummer der IBAN-Regel
     *  @param ibanRegel Nummer der IBAN-Regel
     */
    public void setIbanRegel(String ibanRegel) {
        this.ibanRegel = ibanRegel;
    } // setIbanRegel

    /** Gets ibanRegel - Nummer der IBAN-Regel
     *  @return Nummer der IBAN-Regel
     */
    public String getIbanRegel() {
        return ibanRegel;
    } // getIbanRegel
    //----------------
    /** ibanVersion - Version der Regel */
    protected String ibanVersion;

    /** Sets ibanVersion - Version der Regel
     *  @param ibanVersion Version der Regel
     */
    public void setIbanVersion(String ibanVersion) {
        this.ibanVersion = ibanVersion;
    } // setIbanVersion

    /** Gets ibanVersion - Version der Regel
     *  @return Version der Regel
     */
    public String getIbanVersion() {
        return ibanVersion;
    } // getIbanVersion
    //----------------
    /** okey - original access key */
    protected String okey;

    /** Sets okey - original access key
     *  @param okey original access key
     */
    public void setOkey(String okey) {
        this.okey = okey;
    } // setOkey

    /** Gets okey - original access key
     *  @return original access key
     */
    public String getOkey() {
        return okey;
    } // getOkey
    //----------------

    /** Gets an XML tag for the record
     *  @param namespace namespace for the generated XML tag with colon, or empty
     *  @return an XML element for a BlzDetail record
     */
    public String getXMLTag(String namespace) {
        return namespace + "BlzDetail";
    } // getXMLTag

    /** Assembles all attributes in an object
     *  @return attributes for an XML element representing the bean
     */
    public Attributes getAttributes() {
        String localName = "";
        AttributesImpl attrs = null;
        attrs = new AttributesImpl();
                attrs.addAttribute("", "blz", "blz"          , "CDATA", replaceAttrText(getBlz()));
                attrs.addAttribute("", "fuehrend", "fuehrend", "CDATA", replaceAttrText(getFuehrend()));
                attrs.addAttribute("", "institut", "institut", "CDATA", replaceAttrText(getInstitut()));
                attrs.addAttribute("", "plz", "plz"          , "CDATA", replaceAttrText(getPlz()));
                attrs.addAttribute("", "ort", "ort"          , "CDATA", replaceAttrText(getOrt()));
                attrs.addAttribute("", "inst", "inst"        , "CDATA", replaceAttrText(getInst()));
                attrs.addAttribute("", "instNr", "instNr"    , "CDATA", replaceAttrText(getInstNr()));
                attrs.addAttribute("", "bic", "bic"          , "CDATA", replaceAttrText(getBic()));
                attrs.addAttribute("", "pzMethode", "pzMethode", "CDATA", replaceAttrText(getPzMethode()));
                attrs.addAttribute("", "satzNr", "satzNr"    , "CDATA", replaceAttrText(getSatzNr()));
                attrs.addAttribute("", "aendKnz", "aendKnz"  , "CDATA", replaceAttrText(getAendKnz()));
                attrs.addAttribute("", "loeschung", "loeschung", "CDATA", replaceAttrText(getLoeschung()));
                attrs.addAttribute("", "folgeBlz", "folgeBlz", "CDATA", replaceAttrText(getFolgeBlz()));
                attrs.addAttribute("", "ibanRegel", "ibanRegel", "CDATA", replaceAttrText(getIbanRegel()));
                attrs.addAttribute("", "ibanVersion", "ibanVersion", "CDATA", replaceAttrText(getIbanVersion()));
                attrs.addAttribute("", "okey", "okey"        , "CDATA", replaceAttrText(getOkey()));
        return attrs;

    } // getAttributes

    /** Receive notification of the start of an element.
     *  Looks for the element which contains encoded strings.
     *  @param uri The Namespace URI, or the empty string if the element has no Namespace URI
     *  or if Namespace processing is not being performed.
     *  @param localName the local name (without prefix),
     *  or the empty string if Namespace processing is not being performed.
     *  @param qName the qualified name (with prefix),
     *  or the empty string if qualified names are not available.
     *  @param attrs the attributes attached to the element.
     *  If there are no attributes, it shall be an empty Attributes object.
     *  @throws SAX Exception
     */
    public void startElement(String uri, String localName, String qName, Attributes attrs) throws SAXException {
        try {
            if (false) {
            } else if (qName.equals("BlzDetail")) {
                setBlz             (attrs.getValue("blz"));
                setFuehrend        (attrs.getValue("fuehrend"));
                setInstitut        (attrs.getValue("institut"));
                setPlz             (attrs.getValue("plz"));
                setOrt             (attrs.getValue("ort"));
                setInst            (attrs.getValue("inst"));
                setInstNr          (attrs.getValue("instNr"));
                setBic             (attrs.getValue("bic"));
                setPzMethode       (attrs.getValue("pzMethode"));
                setSatzNr          (attrs.getValue("satzNr"));
                setAendKnz         (attrs.getValue("aendKnz"));
                setLoeschung       (attrs.getValue("loeschung"));
                setFolgeBlz        (attrs.getValue("folgeBlz"));
                setIbanRegel       (attrs.getValue("ibanRegel"));
                setIbanVersion     (attrs.getValue("ibanVersion"));
                setOkey            (attrs.getValue("okey"));
            } else {
                // silently ignore other elements
            }
        } catch (Exception exc) {
            throw new SAXException("invalid attribute value ", exc);
        }
    } // startElement

} // class BlzDetailBeanBase
