/*  IBANRuleBeanBase.java - 
 *  @(#) $Id$
 *  Automatically generated by xtrans/web/xslt/genRecord.xsl at 2014-01-22T14:23:23+01:00
 *  DO NOT EDIT HERE - rather inherit from this class!
 */
package org.teherba.checkdig.account;
import  java.text.SimpleDateFormat;
import  java.sql.Date;
import  java.sql.Timestamp;
import  org.xml.sax.Attributes;
import  org.xml.sax.helpers.AttributesImpl;
import  org.xml.sax.SAXException;

/** .
 */
public class IBANRuleBeanBase {
    /** Readable format for dates */
    protected static final SimpleDateFormat ISO_DATE_FORMAT      = new SimpleDateFormat("yyyy-MM-dd");
    /** Readable format for timestamps with milliseconds */
    protected static final SimpleDateFormat ISO_TIMESTAMP_FORMAT = new SimpleDateFormat("yyyy-MM-dd HH:mm:ss.SSS");

    /** Replaces offending characters in attributes by entities,
     *  and trim right trailing whitespace
     *  @param value value of the attribute
     *  @return string with offending characters replaced by entities
     */
    protected String replaceAttrText(String value) {
        return ("x" + value
                .replaceAll("&" , "&amp;")
                .replaceAll("\'", "&apos;")
                .replaceAll("\"", "&quot;")
               ).trim().substring(1);
    } // replaceAttrText

    /** Source code version */
    public static final String CVSID = "@(#) $Id$";


    /** No-args Constructor for .
     */
    public IBANRuleBeanBase() {
        super();
    } // Constructor

    /** orid - original rule id                */
    protected String orid;

    /** Sets orid - original rule id               
     *  @param orid original rule id               
     */
    public void setOrid(String orid) {
        this.orid = orid;
    } // setOrid

    /** Gets orid - original rule id               
     *  @return original rule id               
     */
    public String getOrid() {
        return orid;
    } // getOrid
    //----------------
    /** okey - original key schema             */
    protected String okey;

    /** Sets okey - original key schema            
     *  @param okey original key schema            
     */
    public void setOkey(String okey) {
        this.okey = okey;
    } // setOkey

    /** Gets okey - original key schema            
     *  @return original key schema            
     */
    public String getOkey() {
        return okey;
    } // getOkey
    //----------------
    /** oblz - original BLZ                    */
    protected String oblz;

    /** Sets oblz - original BLZ                   
     *  @param oblz original BLZ                   
     */
    public void setOblz(String oblz) {
        this.oblz = oblz;
    } // setOblz

    /** Gets oblz - original BLZ                   
     *  @return original BLZ                   
     */
    public String getOblz() {
        return oblz;
    } // getOblz
    //----------------
    /** oacct - original account no             */
    protected String oacct;

    /** Sets oacct - original account no            
     *  @param oacct original account no            
     */
    public void setOacct(String oacct) {
        this.oacct = oacct;
    } // setOacct

    /** Gets oacct - original account no            
     *  @return original account no            
     */
    public String getOacct() {
        return oacct;
    } // getOacct
    //----------------
    /** ocheck - original checking of account no */
    protected String ocheck;

    /** Sets ocheck - original checking of account no
     *  @param ocheck original checking of account no
     */
    public void setOcheck(String ocheck) {
        this.ocheck = ocheck;
    } // setOcheck

    /** Gets ocheck - original checking of account no
     *  @return original checking of account no
     */
    public String getOcheck() {
        return ocheck;
    } // getOcheck
    //----------------
    /** nblz - next BLZ                        */
    protected String nblz;

    /** Sets nblz - next BLZ                       
     *  @param nblz next BLZ                       
     */
    public void setNblz(String nblz) {
        this.nblz = nblz;
    } // setNblz

    /** Gets nblz - next BLZ                       
     *  @return next BLZ                       
     */
    public String getNblz() {
        return nblz;
    } // getNblz
    //----------------
    /** nacct - next account no                 */
    protected String nacct;

    /** Sets nacct - next account no                
     *  @param nacct next account no                
     */
    public void setNacct(String nacct) {
        this.nacct = nacct;
    } // setNacct

    /** Gets nacct - next account no                
     *  @return next account no                
     */
    public String getNacct() {
        return nacct;
    } // getNacct
    //----------------
    /** nbic - next BIC                        */
    protected String nbic;

    /** Sets nbic - next BIC                       
     *  @param nbic next BIC                       
     */
    public void setNbic(String nbic) {
        this.nbic = nbic;
    } // setNbic

    /** Gets nbic - next BIC                       
     *  @return next BIC                       
     */
    public String getNbic() {
        return nbic;
    } // getNbic
    //----------------
    /** niban - next IBAN                       */
    protected String niban;

    /** Sets niban - next IBAN                      
     *  @param niban next IBAN                      
     */
    public void setNiban(String niban) {
        this.niban = niban;
    } // setNiban

    /** Gets niban - next IBAN                      
     *  @return next IBAN                      
     */
    public String getNiban() {
        return niban;
    } // getNiban
    //----------------
    /** nrid - next rule id                    */
    protected String nrid;

    /** Sets nrid - next rule id                   
     *  @param nrid next rule id                   
     */
    public void setNrid(String nrid) {
        this.nrid = nrid;
    } // setNrid

    /** Gets nrid - next rule id                   
     *  @return next rule id                   
     */
    public String getNrid() {
        return nrid;
    } // getNrid
    //----------------
    /** nkey - next key schema                 */
    protected String nkey;

    /** Sets nkey - next key schema                
     *  @param nkey next key schema                
     */
    public void setNkey(String nkey) {
        this.nkey = nkey;
    } // setNkey

    /** Gets nkey - next key schema                
     *  @return next key schema                
     */
    public String getNkey() {
        return nkey;
    } // getNkey
    //----------------

    /** Gets an XML tag for the record
     *  @param namespace namespace for the generated XML tag with colon, or empty
     *  @return an XML element for a IBANRule record
     */
    public String getXMLTag(String namespace) {
        return namespace + "IBANRule";
    } // getXMLTag

    /** Assembles all attributes in an object
     *  @return attributes for an XML element representing the bean
     */
    public Attributes getAttributes() {
        String localName = "";
        AttributesImpl attrs = null;
        attrs = new AttributesImpl();
                attrs.addAttribute("", "orid", "orid"        , "CDATA", replaceAttrText(getOrid()));
                attrs.addAttribute("", "okey", "okey"        , "CDATA", replaceAttrText(getOkey()));
                attrs.addAttribute("", "oblz", "oblz"        , "CDATA", replaceAttrText(getOblz()));
                attrs.addAttribute("", "oacct", "oacct"      , "CDATA", replaceAttrText(getOacct()));
                attrs.addAttribute("", "ocheck", "ocheck"    , "CDATA", replaceAttrText(getOcheck()));
                attrs.addAttribute("", "nblz", "nblz"        , "CDATA", replaceAttrText(getNblz()));
                attrs.addAttribute("", "nacct", "nacct"      , "CDATA", replaceAttrText(getNacct()));
                attrs.addAttribute("", "nbic", "nbic"        , "CDATA", replaceAttrText(getNbic()));
                attrs.addAttribute("", "niban", "niban"      , "CDATA", replaceAttrText(getNiban()));
                attrs.addAttribute("", "nrid", "nrid"        , "CDATA", replaceAttrText(getNrid()));
                attrs.addAttribute("", "nkey", "nkey"        , "CDATA", replaceAttrText(getNkey()));
        return attrs;

    } // getAttributes

    /** Receive notification of the start of an element.
     *  Looks for the element which contains encoded strings.
     *  @param uri The Namespace URI, or the empty string if the element has no Namespace URI
     *  or if Namespace processing is not being performed.
     *  @param localName the local name (without prefix),
     *  or the empty string if Namespace processing is not being performed.
     *  @param qName the qualified name (with prefix),
     *  or the empty string if qualified names are not available.
     *  @param attrs the attributes attached to the element.
     *  If there are no attributes, it shall be an empty Attributes object.
     *  @throws SAX Exception
     */
    public void startElement(String uri, String localName, String qName, Attributes attrs) throws SAXException {
        try {
            if (false) {
            } else if (qName.equals("IBANRule")) {
                setOrid            (attrs.getValue("orid"));
                setOkey            (attrs.getValue("okey"));
                setOblz            (attrs.getValue("oblz"));
                setOacct           (attrs.getValue("oacct"));
                setOcheck          (attrs.getValue("ocheck"));
                setNblz            (attrs.getValue("nblz"));
                setNacct           (attrs.getValue("nacct"));
                setNbic            (attrs.getValue("nbic"));
                setNiban           (attrs.getValue("niban"));
                setNrid            (attrs.getValue("nrid"));
                setNkey            (attrs.getValue("nkey"));
            } else {
                // silently ignore other elements
            }
        } catch (Exception exc) {
            throw new SAXException("invalid attribute value ", exc);
        }
    } // startElement

} // class IBANRuleBeanBase
