#!/usr/bin/perl
#
# phototan.pl - create a random photoTAN image
# @(#) $id$
# Copyright (C) 2013 Dr. Georg Fischer
#
	my $numdots = 25;
	
	my $white = "#ffffff";
	my $red   = "#ff0000";
	my $green = "#00ff00";
	my $blue  = "#0000ff";
	my @colors = ($white, $red, $green, $blue);
	my $dotwidth = 7;                            
	my $dwm1 = $dotwidth - 1;
	my $border = $dotwidth * 2;
	my $radius = int($border * 3 / 4);
	my $x = $border;
	my $y = $border;
	my $offset = $x + 2 * $dotwidth; 
	my $framewidth = ($numdots  * $dotwidth + 2 * $border);
	my $width = $framewidth + 2 * $x;
	my $height = $width;
	open STDOUT, ">phototan.svg";
	print <<"GFis";
<?xml version="1.0" encoding="UTF-8" standalone="no"?>
<!DOCTYPE svg PUBLIC "-//W3C//DTD SVG 1.0//EN"
 "http://www.w3.org/TR/2001/REC-SVG-20010904/DTD/svg10.dtd" [
 <!ATTLIST svg xmlns:xlink CDATA #FIXED "http://www.w3.org/1999/xlink">
]>
<!--Created by photoTAN.pl for org.wikipedia.de at 2013-08-19
    Dr. Georg Fischer, punctum@punctum.com
    The image has the visual appearance of the samples that can be generated on the site
    http://www.crontosign.com
    However, the generated colored dots are totally random, and the black frame
    has a little different shape and no logo.
-->
<svg width="${width}pt" height="${height}pt"
	viewBox="0.00 0.00 ${width} ${height}" 
 	xmlns="http://www.w3.org/2000/svg" 
 	xmlns:xlink="http://www.w3.org/1999/xlink"
 	>
<!-- generated by $0: $gentime -->
<g id="graph0" class="graph" transform="scale(1 1) rotate(0) translate(0 0)">
	<title>photoTAN</title>
	<rect x="$x" y="$y" width="$framewidth" height="$framewidth"
		style="stroke: black; fill: white; stroke-width: $border; stroke-linejoin=round" 
		rx="$radius" ry="$radius" />
GFis
	for (my $iy = 0; $iy < $numdots; $iy ++) {
		for (my $ix = 0; $ix < $numdots; $ix ++) {  
			$x = $offset + $dotwidth * $ix;
			$y = $offset + $dotwidth * $iy;
			my $icolor = int(rand(scalar(@colors)));
			print <<"GFis";
			<rect x="$x" y="$y" width="$dwm1" height="$dwm1" style="fill:@colors[$icolor]" rx="2" ry="2"/>
GFis
		} # for $ix
	} # for $iy
	print <<"GFis";
</g>
</svg>
GFis
