#!/usr/bin/perl

# Generate hashmaps for the mapping of BLZ numbers to check methods
# @(#) $Id: gen_blzmap.pl 71 2009-01-08 20:33:41Z gfis $
# 2014-01-20: store in checkdig/account
# 2008-02-12: Java 1.5 types
# 2007-04-10: with license comments and timestamp
# 2005-10-22
#
# Activation:
#   perl gen_blzmap.pl [-java | -perl] infile > outfile
#-----------------------------------------------------------------
#
#  Copyright 2006 Dr. Georg Fischer <punctum at punctum dot kom>
#
#  Licensed u nder the Apache License, Version 2.0 (the "License");
#  you may not use this file except in compliance with the License.
#  You may obtain a copy of the License at
#
#       http://ww w.apache.org/licenses/LICENSE-2.0
#
#  Unless required  by applicable law or agreed to in writing, software
#  distributed under the License is distributed on an "AS IS" BASIS,
#  WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
#  See the License for the specific language governing permissions and
#  limitations under the License.
#
#-----------------------------------------------------------------
use strict;

    my $proglan = shift (@ARGV);
    my $infile = shift (@ARGV);
    open (IN, "<", $infile) || die "cannot read $infile";
    my @max = ( 0, 0, 0, 0, 0
              , 0, 0, 0, 0, 0 );
    my @cm_max = @max;

	my ($sec, $min, $hour, $mday, $mon, $year, $wday, $yday, $isdst) = localtime (time);
	$mon += 1;
	$year += 1900;
	my $timestamp   = sprintf ("%04d-%02d-%02dT%02d:%02d:%02d", $year, $mon, $mday, $hour, $min, $sec);

    while (<IN>) {
        next if ! m[\d];
        my ($count, $blz4, $cm) = split;
        if ($count > $max[$blz4]) {
            # print "$count\t$blz4\t$cm\n";
            $max[$blz4] = $count;
            $cm_max[$blz4] = $cm;
        }
    } # while
    close (IN);

    my $blz4 = 0;
    while ($blz4 < 10) {
            # print "$blz4\t" .  $cm_max[$blz4] . "\n";
        $blz4 ++;
    }

    my %cm_blz;
    my $blzfile = shift (@ARGV);
    open  (BLZ, "<", $blzfile) || die "cannot read $blzfile";
    while (<BLZ>) {
        next if substr($_, 8, 1) ne "1";
        my $blz = substr ($_, 0, 8);
        my $cm  = substr ($_, 150, 2);
        my $blz4 = substr ($blz, 3, 1); # position 4
        if ($cm_max[$blz4] ne $cm) {
            $cm_blz{$blz4} .= ",$blz>$cm";
        }
    } # while
    close (BLZ);
    if ($proglan =~ m[java]i) {
        & gen_java ();
    }
    else {
        & gen_perl ();
    }

sub gen_java {
    print <<"GFis";
/*
 *  Mapping from BLZ numbers to check m    ethods
 *  \@(#)   \$Id\$
 *  $timestamp: generated by test/blz/gen_blzmap.pl, DO NOT EDIT HERE!
 */
/*
 * Copyright 2006 Dr. Georg Fischer <punctum at punctum dot kom>
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
package org.teherba.checkdig.account;
import  java.io.BufferedReader;
import  java.io.FileReader;
import  java.util.HashMap;

/** Mapping from BLZ numbers to check methods.
 *  \@author Dr. Georg Fischer
 */
public class BlzCheckMap {
    public final static String CVSID = "\@(#) \$Id\$";

GFis
#-----------------------------------------
    $blz4 = 0;
    while ($blz4 < 10) {
        print <<"GFis";
    /** Hash map for the BLZs with digit \'$blz4\' in place 4 */
    private static HashMap/*<1.5*/<String, String>/*1.5>*/ map$blz4 = new HashMap/*<1.5*/<String, String>/*1.5>*/(512);
GFis
        $blz4 ++;
    }
#-----------------------------------------
    print <<'GFis';
    static {
GFis
#-----------------------------------------
    for (my $blz4 = 0; $blz4 < 10; $blz4 ++) {
        # print "$blz4\t", $cm_blz{$blz4}, "\n";
        print "\ \ \ \ \ \ \ \ map$blz4.put(\"default\", \"$cm_max[$blz4]\");\n"; # the default mapping
        foreach my $pair (split (/\,/, substr ($cm_blz{$blz4}, 1))) {
            my ($blz, $cm) = split (/\>/, $pair);
            print "\ \ \ \ \ \ \ \ map$blz4.put(\"$blz\", \"$cm\");\n";
        } # foreach $pair
        print "\n";
    } # foreach $blz4
#-----------------------------------------
    print <<'GFis';
    }

    /** No-args constructor
     */
    public BlzCheckMap() {
    } // BlzCheckMap

    /** Gets the check method number for a BLZ
     *      @param blz BLZ for which the check method should be determined
     *  @return check met    hod number (00..99..A9..B8)
     */
    public String getMethod(String blz) {
        Object result = "";
        try {
            char blz4 = blz.charAt(3);
                // digit at position 4 = net id
            switch (blz4) {
GFis
        for (my $blz4 = 0; $blz4 < 10; $blz4 ++) {
            print <<"GFis";
                case \'$blz4\':
                    result = map$blz4.get(blz);
                    if (result == null) {
                        result = map$blz4.get("default");
                    }
                    break;
GFis
        } # for $blz4
        print <<'GFis';
            } // switch
        } catch (Exception exc) {
            System.out.println(exc.getMessage());
            exc.printStackTrace( );
        } // catch
        return (String) result;
    } // getMethod

    /** Test Frame, read lines with method id, account number, blz
     *  and check whether the same method is returned by <em>getMethod</em>.
     *  @param args commandli    ne arguments: input-filename
     */
    public static void main (String args[]) {
        try {
            int iarg = 0; // index in args
            int iadd = 1; // default: insert before 1st element
            int irep = 0; // do not replace
            int iblz = 2; //  default: BLZ in 2nd element
            while (iarg < args.length && args[iarg].startsWith("-")) {
                String opt = args[iarg ++];
                if (false) {
                } else if (opt.startsWith("-b")) {
                    if (opt.length() > 2) {
                        iblz = Integer.parseInt(opt.substring(2));
                    } else {
                        iblz = Integer.parseInt(args[iarg ++]);
                    }
                } else if (opt.startsWith("-a")) {
                    irep = 0;
                    if (opt.length() > 2) {
                        iadd = Integer.parseInt(opt.substring(2));
                    } else {
                        iadd = Integer.parseInt(args[iarg ++]);
                    }
                } else if (opt.startsWith("-r")) {
                    iadd = 0;
                    if (opt.length() > 2) {
                        irep = Integer.parseInt(opt.substring(2));
                    } else {
                        irep = Integer.parseInt(args[iarg ++]);
                    }
                }
            } // while iarg
            String line; // from test input file
            BufferedReader infile = new BufferedReader (new FileReader (args[iarg ++]));
            boolean busy = true; // for loop control
            BlzCheckMap mapper = new BlzCheckMap();

            while (busy) {
                line = infile.readLine();
                if (line == null) { // EOF
                    busy = false;
                } else { // not EOF
                    if (line.length() >= 4 && ! line.startsWith("#")) {
                        line = line.trim();
                        String  elements[]   = line.split("\\s+");
                        String blz      = elements[iblz - 1];
                        String method   = mapper.getMethod(blz);
                        if (iadd > 0) { // insert before elements[iadd - 1]
                            for (int ielem = 0; ielem < elements.length; ielem ++) {
                                if (iadd - 1 == ielem) {
                                    System.out.print(method + "\t");
                                }
                                if (ielem > 0) {
                                    System.out.print("\t");
                                }
                                System.out.print(elements[ielem]);
                            } // for ielem
                        } else { // replace elements[irep - 1]
                            elements[irep - 1] = method;
                            for (int ielem = 0; ielem < elements.length; ielem ++) {
                                if (ielem > 0) {
                                    System.out.print("\t");
                                }
                                System.out.print(elements[ielem]);
                            } // for ielem
                        }
                        System.out.println();
                    } // length >= 4
                    else {
                        System.out.println(line);
                    }
                } // not EOF
            } // while busy
        } // try
        catch (Exception exc) {
            System.out.println(exc.getMessage());
            exc.printStackTrace();
        } // catch
    } // main
} // BlzCheckMap
GFis
} # gen_java

sub gen_perl {
    print <<"GFis";
#!/usr/bin/perl

#
#  Copyright 2006 Dr. Georg Fischer <punctum at punctum dot kom>
#
#  Licensed under the Apache License, Version 2.0 (the "License");
#  you may not use this file except in compliance with the License.
#  You may obtain a   copy of the License at
#
#       http://www.apache.org/licenses/LICENSE-2.0
#
#  Unless required by applicable  law or agreed to in writing, software
#  distributed under the License is distributed on an "AS IS" BASIS,
#  WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
#   See the License for the specific language governing p ermissions and
#  limitations under the License.
#
#------------------------------------------------------------
#   Mapping from BLZ numbers to check methods
#   \@(#) \$Id\$
#   $timestamp: generated by gen_blzmap.pl, DO NOT EDIT HERE!
#------------------------------------------------------------

use strict;
#-----------------------------------------
GFis
    my $blz4 = 0;
    while ($blz4 < 10) {
        print <<"GFis";
    # Hash map for the BLZs with digit \'$blz4\' in place 4
    my \%map$blz4 = ("default", \"$cm_max[$blz4]\"
GFis
        foreach my $pair (split (/\,/, substr ($cm_blz{$blz4}, 1))) {
            my ($blz, $cm) = split (/\>/, $pair);
            print "\ \ \ \ \ \ \ \ , \"$blz\", \"$cm\"\n";
        } # foreach $pair
        print "\ \ \ \ \ \ \ \ );\n";
        $blz4 ++;
    }
    print <<'GFis';
main:
    #   Test Frame, read lines with method id, account number, blz
    #   and check whether the same method is returned by <em>getmethod</em>.
    #   activation:
    #   perl add_method.pl [-b n [-a m | -r m]] input-filename
    #       -b  column number of BLZ (1,2 ..., default 2)
    #       -a  a  dd method before this column number (default 1)
    #       -r  replace method in this column number
    #
    my $iblz = 2;
    my $iadd = 1;
    my $irep = 0;
    my  $opt;
    while (scalar (@ARGV) > 0 && $ARGV[0] =~ m[\A\-]) {
        $opt = shift (@ARGV);
        if (0) {
        } elsif ($opt =~ m[b]) {
            if ($opt =~ m[(\d+)]) {
                $iblz = $1;
            } else {
                $iblz = shift (@ARGV);
            }
        } elsif ($opt =~ m[a]) {
            $irep = 0;
            if ($opt =~ m[(\d+)]) {
                $iadd = $1;
            } else {
                $iadd = shift (@ARGV);
            }
        } elsif ($opt =~ m[r]) {
            $iadd = 0;
            if ($opt =~ m[(\d+)]) {
                $irep = $1;
            } else {
                $irep = shift (@ARGV);
            }
        }
    } # while options

    if (0) {
        print "iblz=$iblz, iadd=$iadd, irep=$irep\n";
        print "50040033->", $map4{"50040033"}, ";\n";
        print "50040000->", $map4{"50040000"}, ";\n";
        print "default->" , $map4{"default"}, ";\n";
    }
    while (<>) {
        next if length ($_) < 4 || m[\A\#];
        s[\s+\Z][]; # chompr
        my @elements = split;
        my $blz = $elements[$iblz - 1];
        # print "iblz=$iblz, iadd=$iadd, irep=$irep, blz=$blz;\n";
        my $method = & get_method ($blz);
        next if $method eq "09";
        if ($iadd > 0) {
            splice (@elements, $iadd - 1, 0, ($method)); # insert it
        }
        else { # $irep > 0 - replace it
            $elements[$irep - 1] = $method;
        }
        print join ("\ \ \ \ ", @elements), "\n";
    } # while <>
#-----------------------------------------
sub get_method {
    #   Gets the check method number for a BLZ
    #   @param blz BLZ for which the check method should be determined
    #   @return check method number (00..99..A9..B8)

    my $result;
    my $d = ""; # or "" if not to ignore "default" BLZs
    my ($blz) = @_;
    my $blz4 = substr($blz, 3, 1); # digit at position 4 = net id
    if (0) {
GFis
    $blz4 = 0;
    while ($blz4 < 10) {
        print <<"GFis";
    } elsif (\$blz4 eq \"$blz4\") {
        \$result = \$map$blz4\{\$blz\};
        if (\$result eq \"\") {\n"
            \$result = \$d . \$map$blz4\{\"default\"};
        }
GFis
        $blz4 ++;
    } # while $blz4
    print <<'GFis';
    }
    return $result;
} # sub get_method
#-----------------------------------------
GFis
} # gen_perl

__DATA__
    129 0   09
      3 1   00
      2 1   01
      3 1   06
      1 1   08
     86 1   09
      8 1   10
     65 1   13
      1 1   18
      2 1   19
     15 1   24
      1 1   28
      2 1   32

301500011Clearingkto Westdeutsche Landesbank Düsseldorf            40002Düsseldorf                         Clear West LB Düsseldorf                   09043029U000000000
401500011Clearingkto Westdeutsche Landesbank Münster               48134Münster, Westf                     Clear West LB Münster                      09043030U000000000
721200791Bayer Hypo- und Vereinsbank                               85017Ingolstadt, Donau                  Hypovereinsbk Ingolsta                     99044062U000000000
701210991Bayer Hypo- und Vereinsbank Scheckeinzug (GSE)            85609Aschheim                           Hypovereinsbk GSE                          95050601U000000000
370307001WW Bank                                                   50672Köln                               WW Bank                                    19052797A000000000
711600001Volksbank Raiffeisenbank Mangfalltal-Rosenheim            83022Rosenheim, Oberbay                 VR-Bk Mangfalltal-Rosenheim68159           88052794A000000000
700117001Von der Heydt-Kersten & Söhne                             80538München                            Von der Heydt München                      10052771U000000000
390200001Aachener Bausparkasse                                     52001Aachen                             Aachener Bauspk Aachen          AABSDE31XXX09043859U000000000
390500001Sparkasse Aachen                                          52059Aachen                             Sparkasse Aachen           53408AACSDE33XXX00004859U000000000
510106001Aareal Hyp                                                65011Wiesbaden                          Aareal Hyp                      AAHBDE5WXXX09051486U000000000
100104241Aareal Bank                                               10666Berlin                             Aareal Bank                26910AARBDE5W10009004795U000000000
510108001Aareal Bank Zw L                                          65011Wiesbaden                          Aareal Bank Zw L Wiesbaden 26715AARBDE5W10809013590U000000000
200104241Aareal Bank                                               20009Hamburg                            Aareal Bank                26911AARBDE5W20009006328U000000000
250104241Aareal Bank                                               30014Hannover                           Aareal Bank                26912AARBDE5W25009006302U000000000
360104241Aareal Bank                                               45009Essen, Ruhr                        Aareal Bank Essen          26913AARBDE5W36009004846U000000000
500104241Aareal Bank                                               60284Frankfurt am Main                  Aareal Bank                26914AARBDE5W50009004824U000000000
550104241Aareal Bank                                               55027Mainz a Rhein                      Aareal Bank                26915AARBDE5W55009006295U000000000
600104241Aareal Bank                                               70191Stuttgart                          Aareal Bank                26916AARBDE5W60009006466U000000000
